[package]
name = "wasi-experimental-http"
version = "0.1.0"
authors = ["Radu Matei <radu.matei@microsoft.com>"]
edition = "2018"

[dependencies]
http = "0.2"
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0.100", features = ["derive"] }
