[package]
name = "wasi-experimental-http-wasmtime"
version = "0.1.0"
authors = ["Radu Matei <radu.matei@microsoft.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bytes = "1"
futures = "0.3"
http = "0.2"
reqwest = { version = "0.11", default-features = true, features = ["json", "blocking"] }
tokio = { version = "1.1", features = ["full"] }
url = "2.2.1"
wasmtime = "0.24"
wasmtime-wasi = "0.24"
wasi-common = "0.24"
wasi-experimental-http = {path = "../wasi-experimental-http"}
