name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: rustup target add wasm32-wasi && cargo build --verbose
    - name: Run simple test
      shell: bash
      run:   |
            if [ "$RUNNER_OS" == "Windows" ]; then
                  # Attempting to run the unit tests on Windows
                  # results in the linker failing because it cannot
                  # compile the Rust client library because of the
                  # missing external symbols, so we are only running
                  # the integration tests on Windows.
                  cargo test -- --nocapture
            else
                  cargo test --all -- --nocapture
            fi
